name: Build and Sign APK

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Execute build script
      run: |
        sh setup
        cp bashrc ~/.bashrc
        chmod +x license
        sudo groupadd vagrant
        sudo sh license

    - name: Build and Sign APK
      run: |
        whereis javac
        sudo update-alternatives --list java
        sudo chmod +x gradlew
        ./gradlew clean
        sudo ./gradlew assembleRelease
        ls -la app/build/outputs/apk/release/
         sudo jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks -storepass harryThanatos app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk KaizenVPN
         
         sudo jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks -storepass harryThanatos app/build/outputs/apk/release/app-x86-release-unsigned.apk KaizenVPN
         
         
         sudo jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks -storepass harryThanatos app/build/outputs/apk/release/app-x86_64-release-unsigned.apk KaizenVPN
         
         
        sudo jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks -storepass harryThanatos app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned.apk KaizenVPN
    - name: Upload the signed APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release-signed
        path: app/build/outputs/apk/release/*.apk