name: Build and Sign APK

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java 17 (Temurin)
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set JAVA_HOME
      run: |
        echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))" >> $GITHUB_ENV
        echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
      shell: bash

    - name: Execute build script
      run: |
        sudo sh setup
        cp bashrc ~/.bashrc
        sudo chmod +x license
        sudo groupadd vagrant
        sudo sh license

    - name: Build and Sign APK
      run: |
        sudo chmod +x gradlew
        sh gradlew clean
        sudo sh gradlew assembleRelease
        ls -la app/build/outputs/apk/release/

    - name: Upload the signed APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release-signed
        path: app/build/outputs/apk/release/*.apk
